# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"

  before_all do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "600"
  end

  after_all do |lane|
    slack(message: "리빗 iOS 배포 완료 ⭐️")
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false)
  end

  lane :test do
    scan(
      project: "Rebit.xcodeproj",
      devices: ["iPhone 16 Pro"]
    )
  end

  lane :beta do
    
    # 키체인 생성
    create_keychain(
      name: ENV["KEYCHAIN_NAME"],
      password: ENV["KEYCHAIN_PASSWORD"],
      timeout: 1800,
      default_keychain: true,
      unlock: true,
      lock_when_sleeps: false
    )

    # APP STORE CONNECT API KEY 및 Fastlane Match 설정
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
    )

    match(
      git_url: "git@github.com:dream7739/fastlane-match-iOS.git",
      storage_mode: "git",
      type: "appstore",
      readonly: true,
      keychain_name: ENV["KEYCHAIN_NAME"],
      keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )

    # 빌드 넘버 자동증가 
    increment_build_number(xcodeproj: "Rebit.xcodeproj")
    build_ios_app(
      scheme: "Rebit",
      destination: "platform=iOS Simulator,name=iPhone 16 Pro"
    )

    # 슬랙 연동
    slack(message: "리빗 iOS 배포 진행중 ⭐️")

    # 테스트 플라이트 업로드
    upload_to_testflight
  end
end
